[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# 持久化存储SQLite数据库
[[deploy.volumes]]
name = "poi-storage"
mountTo = "/mnt/data"